### ISSUE TITLE
Windows make version

### ISSUE THREAD

**Issue by alexxucui** [udacity/CarND-Extended-Kalman-Filter-Project#13]
Hi the link you provided for make for windows is 3.8.1 but the minimum requirement is 4.1. I have run the model on both windows and ubuntu and see very different results. Not sure if it is the make issue here. 
https://discussions.udacity.com/t/large-discrepancy-in-results-running-on-windows-and-ubuntu/229811

**Comment by cameronwp** [comment]
Oh very weird. Investigating.

**Comment by rohts-patil** [comment]
Is there any workaround for this. Or can Udacity provide the necessary make setup file?

**Comment by cameronwp** [comment]
@rohts-patil, you're seeing the same thing? Still trying to find the source of this one.

I'm assuming both of you are using make 3.8.1?

**Comment by cameronwp** [comment]
Have either of you tried using the Windows bash implementation to install / execute make?

**Comment by rohts-patil** [comment]
Yes, I tried that. But while downloading the source for make using wget it throws this error:- Cannot write to ‘make-4.1.tar.gz’ (Permission denied).

**Comment by cameronwp** [comment]
This may be a silly question, but have you tried `sudo`? I'm unfamiliar with bash on Windows.

**Comment by rohts-patil** [comment]
This is the [post](http://www.ramoonus.nl/2010/01/01/howto-install-bash-4-1-in-linux/) that I followed.

**Comment by propellingbits** [comment]
It throw me down in a rabbit hole:
"On windows, you may need to run: cmake .. -G "Unix Makefiles" && make"

Safe route - So first install VS community edition 2017 (one option) then "cmake .. && make"

**Comment by mvirgo** [comment]
Looks like no recent posts, so going to close out. I think the updates to CMakeLists.txt in the meantime have helped, plus we now have a in-classroom workspace environment that should help for any students having difficulties on Windows.
