### ISSUE TITLE
variable timestamp_ bits

### ISSUE THREAD

**Issue by jinchenglee** [udacity/CarND-Extended-Kalman-Filter-Project#17]
I noticed timestamp_ in GroundTruthPackage class uses long (32bits) but in MeasurementPackage it uses long long (64 bits). Shouldn't we use same number of bits in both places? And it seems 32 bits cannot hold all widths of time stamps. 

It probably won't report out error as we care only about delta in time stamps, but it will incur truncation by long(32bits) I believe.

**Comment by sookinoby** [comment]
@jinchenglee This causes a bug in windows mingw. I had hard time figuring out what was wrong. Did you create a pull request?

**Comment by jinchenglee** [comment]
I did, but I do not see a response.

**Comment by jwdunn1** [comment]
The declaration of previous_timestamp_ in FusionEKF.h should be also be long long. (I lost time tracking that one down.)

**Comment by dyh1213** [comment]
Come on ... this issue just cost me a week of frustration.

**Comment by andrewpaster** [comment]
Hi, I updated the repo with the long long declarations. @jinchenglee I don't see a pull request for this, did you close it at some point?
