### ISSUE TITLE
Segmentation fault on OS X

### ISSUE THREAD

**Issue by jaredjxyz** [udacity/CarND-Extended-Kalman-Filter-Project#19]
Running the project using

./ExtendedKF ../data/sample-laser-radar-measurement-data-1.txt output.txt > error.txt

Gives me the following error

> [1]    27390 segmentation fault  ./ExtendedKF ../data/sample-laser-radar-measurement-data-1.txt output.txt >

(This error appears without piping to a file as well, but I piped to a file so I could attach the output to this post)

OS X version 10.12.3
CMake 3.7.2
Make 3.81 (I couldn't find a way to update OS X to Make 4.1)

And attached are the relevant files
[output.txt](https://github.com/udacity/CarND-Extended-Kalman-Filter-Project/files/884428/output.txt)
[error.txt](https://github.com/udacity/CarND-Extended-Kalman-Filter-Project/files/884430/error.txt)
[sample-laser-radar-measurement-data-1.txt](https://github.com/udacity/CarND-Extended-Kalman-Filter-Project/files/884431/sample-laser-radar-measurement-data-1.txt)

**Comment by mvirgo** [comment]
Closing this out based on age + no further comments, but the most common Segmentation Faults on EKF (and UKF) usually relate to index out of bounds issues on arrays and vectors (it could also occur if a pointer goes somewhere awry at some point).
