### ISSUE TITLE
install-mac.sh does not work from Mac OS 10.11 upwards

### ISSUE THREAD

**Issue by pierluigiferrari** [udacity/CarND-Extended-Kalman-Filter-Project#35]
I've just tried to install uWebSocket on Mac OS Sierra using `install-mac.sh` and got the following error:

```
CMake Error at cmake_install.cmake:39 (file):
   file cannot create directory: /usr/lib64.  Maybe need administrative
   privileges.

make: *** [install] Error 1
```

Apparently the System Integrity Protection introduced in Mac OS 10.11 prohibits even super users from making changes to /usr.

I tried to change the `cmake ..` line to

`cmake .. -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DOPENSSL_LIBRARIES=/usr/local/opt/openssl/lib`,

but I am still getting the same error.

**Comment by dyelax** [comment]
I found a workaround here: https://discussions.udacity.com/t/cant-install-uwebsockets/247800/10?u=matthew_cooper

**Comment by pierluigiferrari** [comment]
@dyelax Thanks a lot!

Udacity should update the shell script accordingly.

**Comment by subodh-malgonde** [comment]
@pierluigiferrari Did this workaround work for you? This workaround was included in the project repo 4 days ago in this commit https://github.com/udacity/CarND-Extended-Kalman-Filter-Project/commit/8260ffbbec4d311127124da90345fa0a58316a7a. So with the latest install-mac.sh file it should work fine.

**Comment by pierluigiferrari** [comment]
@subodh-malgonde but the repo says that `install-mac.sh` and `install-ubuntu.sh` were both last updated 20 days ago? what branch do you mean? they were not updated in master.

**Comment by subodh-malgonde** [comment]
I mean't to say the `cmakepatch.txt` was missing. It was added 5 days ago. Please see this commit https://github.com/udacity/CarND-Extended-Kalman-Filter-Project/commit/8260ffbbec4d311127124da90345fa0a58316a7a

**Comment by awbrown90** [comment]
Sorry, thought this issue had been closed before. cmakepatch.txt was added correcting the issue.
