### ISSUE TITLE
readme need to update for "Run it" instruction after merge project_v2

### ISSUE THREAD

**Issue by MichaelTien8901** [udacity/CarND-Extended-Kalman-Filter-Project#39]
Basic Build Instructions

Clone this repo.
Make a build directory: mkdir build && cd build
Compile: cmake .. && make
On windows, you may need to run: cmake .. -G "Unix Makefiles" && make
Run it: ./ExtendedKF ~~path/to/input.txt path/to/output.txt. You can find some sample inputs in 'data/'.~~
~~eg. ./ExtendedKF ../data/obj_pose-laser-radar-synthetic-input.txt~~

**Comment by baumanab** [comment]
Thank you, this has been aligned.
