### ISSUE TITLE
cmake, make, and gcc/g++

### ISSUE THREAD

**Issue by philbort** [udacity/CarND-Extended-Kalman-Filter-Project#4]
Without any coverage in the course material leading to this project, we probably shouldn't assume every student knows what below means.

```
cmake >= v3.5
make >= v4.1
gcc/g++ >= v5.4
```

**Comment by cameronwp** [comment]
Agreed. I've added installation instructions to the project info page.

**Comment by cameronwp** [comment]
Also added installation instructions to the project README. Reopen if you'd like to see more.

**Comment by philbort** [comment]
Looks good to me. Thanks! The only thing I can think about is maybe mention if we have homebrew that might be the easiest way to install cmake:

`brew install cmake`
