### ISSUE TITLE
install_ubuntu.sh doesnot work for 14.04

### ISSUE THREAD

**Issue by sumanth-nirmal** [udacity/CarND-Extended-Kalman-Filter-Project#49]
`libuv1-dev` can't be installed using apt on ubuntu 14.04, which causes 'install_ubuntu.sh' to fail.
The bash script can be fixed by downloading the .deb(https://packages.ubuntu.com/xenial/amd64/libuv1-dev/download) and installing it (in case of 14.04).

**Comment by RobinCPC** [comment]
Need to install `libuv1` before installing `libuv1-dev` (for me, on ubuntu 14.04 64-bit). 
The [link](https://packages.ubuntu.com/xenial/amd64/libuv1/download) to download. 

Edit:
Just find out that Udacity staff (thanks!) had provide [Tips for setting up environment](https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/0949fca6-b379-42af-a919-ee50aa304e6a/lessons/f758c44c-5e40-4e01-93b5-1a82aa4e044f/concepts/23d376c7-0195-4276-bdf0-e02f1f3c665d)

Here's the part for libuv1-dev:
```bash
sudo add-apt-repository ppa:acooks/libwebsockets6
sudo apt-get update
sudo apt-get install libuv1.dev
```

**Comment by baumanab** [comment]
I'm glad the updated instructions worked out!
