### ISSUE TITLE
install-mac.sh installs OpenSSL with homebrew, but does not find it automatically

### ISSUE THREAD

**Issue by mbachm** [udacity/CarND-Extended-Kalman-Filter-Project#51]
The install-mac.sh fails and produces the following error:

`CMake Error at /usr/local/Cellar/cmake/3.8.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.8.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.8.2/share/cmake/Modules/FindOpenSSL.cmake:387 (find_package_handle_standard_args)
  CMakeLists.txt:8 (find_package)`

I had to change `cmake ..` with `cmake -DOPENSSL_ROOT_DIR=/usr/local/Cellar/openssl/1.0.2l -DOPENSSL_LIBRARIES=/usr/local/Cellar/openssl/1.0.2l/lib ..` to make the script work as mentioned in #32 .

Can you adjust the script that it automatically detects the openssl root dir?

**Comment by mvirgo** [comment]
Looks like this was fixed in 9dc2e6f - thanks for pointing out.
