### ISSUE TITLE
Unable to install uWebSockets with ./install-mac.sh script in Make

### ISSUE THREAD

**Issue by manopaul** [udacity/CarND-Extended-Kalman-Filter-Project#56]
Getting an error when running make to get uWebSockets to install stating that the Localization file is not found. Unable to proceed.
Assistance appreciated. 

![image](https://user-images.githubusercontent.com/5560792/28847924-985bcdf8-76d6-11e7-8102-79a79c5513da.png)

**Comment by baumanab** [comment]
Sorry for the technical issues.   I'm guessing this issue has been resolved.  If it has not, please let us know and we can reopen.  FYI, environment setup instructions were updated in the Fall and can be found [here](https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/0949fca6-b379-42af-a919-ee50aa304e6a/lessons/f758c44c-5e40-4e01-93b5-1a82aa4e044f/concepts/16cf4a78-4fc7-49e1-8621-3450ca938b77)
