### ISSUE TITLE
Eigen members within structures need to be aligned

### ISSUE THREAD

**Issue by jwdinius** [udacity/CarND-Extended-Kalman-Filter-Project#57]
I had been using Eigen with another application and noticed a recurring seg fault when trying to end the application.  valgrind pointed me to a memory alignment issue within Eigen, which led me to this:

https://eigen.tuxfamily.org/dox/group__TopicStructHavingEigenMembers.html

I believe that your code for all term 2 projects that use Eigen needs to include EIGEN_MAKE_ALIGNED_OPERATOR_NEW in the public members area wherever an Eigen container is declared within a struct/class.

**Comment by mvirgo** [comment]
As long as it's only right at the exit of the code, doesn't seem like too big of an item, but if you'd like to create a PR as an example for this project, we can look into it further for the others as well.
