### ISSUE TITLE
Windows 10 environment setup fails when using Ubuntu 18

### ISSUE THREAD

**Issue by nvphadnis** [udacity/CarND-Extended-Kalman-Filter-Project#70]
./install-ubuntu.sh does not complete unless the Ubuntu version is 16.04. I came across complaints on the forum that versions older than 16.04 face similar issues but even a newer version (18) did not succeed.

**Comment by mvirgo** [comment]
Closing this out based on no further comments and that we now have a Linux-based Workspace available in the classroom; otherwise would need to also get any error/failure information in order to proceed.
