### ISSUE TITLE
Segmentation fault (core dumped) with Term 2 Simulator in Ubuntu Bash on Windows 10

### ISSUE THREAD

**Issue by nbibin001** [udacity/CarND-Extended-Kalman-Filter-Project#74]
I was setting up the environment for the EKF project. I installed the Ubuntu bash on Windows 10, and I was trying to run the simulator. 

First I extracted the simulator to a folder, changed the permission to execute the file
chmod ug+x ./term2_sim.x86_64

Then I found that in order to run the exe there are some dependencies, so I installed all the dependencies it complained for
sudo apt-get install libglu1
sudo apt-get install libxcursor1
sudo apt-get install libxrandr2

But now wen I run this command to run the simulator. 
sudo ./term2_sim.x86_64

I get this error

"Segmentation fault (core dumped)"

I am not sure if I am doing something wrong, could you please help ?

**Comment by mvirgo** [comment]
Hi there! Please note that usually support issues should usually go through Student Hub in the classroom first.

A segmentation fault will occur with this project (or many other C++ projects) in a few situations. Two of the more common ones are:
1) Trying to access out of bounds in an array
2) Trying to run the code when a function is not returning something as expected.

For this project, the second issue is the most likely - take a look at `tools.cpp`. If you have not yet implemented either of the functions there, your code is trying to get either a vector or a matrix from these functions, but they don't return anything yet! So if you have not implemented anything in that file yet, a Segmentation Fault will likely occur.

**Comment by mvirgo** [comment]
No further comments in a month; closing.
