### ISSUE TITLE
the weblink doesn't work

### ISSUE THREAD

**Issue by SeokLeeUS** [udacity/CarND-Extended-Kalman-Filter-Project#76]
This hyperlink was shown in readme even if I am part of Nano degree program. 

https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/0949fca6-b379-42af-a919-ee50aa304e6a/lessons/f758c44c-5e40-4e01-93b5-1a82aa4e044f/concepts/382ebfd6-1d55-4487-84a5-b6a5a4ba1e47

**Comment by mvirgo** [comment]
Nice catch! That link was for the three-term version of the program. I have removed the link and clarified to visit the Project Resources page in the classroom.
