### ISSUE TITLE
Issue when the phi values are in 3rd quadrant(180 to 270 degree)

### ISSUE THREAD

**Issue by bheeshmarayabv** [udacity/CarND-Extended-Kalman-Filter-Project#84]
Hello,

I am using this code for experiments for other synthetic data where data is generated by matlab , I see that estimations are totally wrong when the (x, y)  both are negative which means the when phi is 180 to 270. Can you please let me know if you have any idea ?

Regards
Bheeshma

**Comment by theogdz** [comment]
The angle has to be normalized between -pi and pi. Therefore, it will neither work in the 3rd nor 4th quadrant.

**Comment by UAnjali** [comment]
Hi @bheeshmarayabv,
We hope that your issue is resolved.  We encourage such issues to be raised on the Knowledge hub so that our experienced mentors can chime in and new students can also learn from the discussion thread. 
Thank you
